<%

query_person_cost = ""
query_person_cost = query_person_cost + " SELECT  A.EMP_NO                                                                                                                                                   "  
query_person_cost = query_person_cost + "           , GENERAL_CNT                                                                                                                                            "
query_person_cost = query_person_cost + "           , GENERAL_COST                                                                                                                                           "
query_person_cost = query_person_cost + "           , OVERTIME_CNT                                                                                                                                           "
query_person_cost = query_person_cost + "           , OVERTIME_COST                                                                                                                                          "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, GAS_KM2 , GAS_KM)  AS GAS_KM                                                                                                          "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, GAS_UNIT2 , GAS_UNIT)   AS GAS_UNIT                                                                                                   "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, ROUND(GAS_KM2    * A.GAS_UNIT2    / 7) , GAS_COST) AS GAS_COST                                                                        "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, GASOL_KM2 , GASOL_KM)  AS  GASOL_KM                                                                                                   "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, GASOL_UNIT2 , GASOL_UNIT) AS GASOL_UNIT                                                                                               "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, ROUND(GASOL_KM2  * A.GASOL_UNIT2  / LITER ) , GASOL_COST) AS GASOL_COST                                                               "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, DIESEL_KM2 , DIESEL_KM)  AS  DIESEL_KM                                                                                                "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, DIESEL_UNIT2 , DIESEL_UNIT) AS  DIESEL_UNIT                                                                                           "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, ROUND(DIESEL_KM2 * A.DIESEL_UNIT2 / LITER) , DIESEL_COST) AS DIESEL_COST                                                              "
query_person_cost = query_person_cost + "           , IF(COMPANY_YN>0, (GAS_KM2 + DIESEL_KM2 +  GASOL_KM2) * 25 ,SOMOPUM_COST ) AS SOMOPUM_COST                                                              "
query_person_cost = query_person_cost + "           , FARE_CNT                                                                                                                                               "
query_person_cost = query_person_cost + "           , FARE_COST                                                                                                                                              "
query_person_cost = query_person_cost + "           , OIL_CASH_COST                                                                                                                                          "
query_person_cost = query_person_cost + "           , REPAIR_COST                                                                                                                                            "
query_person_cost = query_person_cost + "           , PARKING_COST                                                                                                                                           "
query_person_cost = query_person_cost + "           , TOLL_COST                                                                                                                                              "
query_person_cost = query_person_cost + "           , CARD_COST                                                                                                                                              "
query_person_cost = query_person_cost + "           , CARD_COST_VAT                                                                                                                                          "
query_person_cost = query_person_cost + "           , RETURN_CASH                                                                                                                                            "
query_person_cost = query_person_cost + "           , JUYOO_CARD_COST                                                                                                                                        "
query_person_cost = query_person_cost + "           , JUYOO_CARD_COST_VAT                                                                                                                                    "
query_person_cost = query_person_cost + "           , VARIATION_MEMO                                                                                                                                         "
query_person_cost = query_person_cost + "           , GENERAL_COST_01                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_02                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_03                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_04                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_05                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_06                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_07                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_08                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_09                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_10                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_11                                                                                                                                        "
query_person_cost = query_person_cost + "           , GENERAL_COST_12                                                                                                                                        "
query_person_cost = query_person_cost + "           , COMPANY_YN                                                                                                                                             "
query_person_cost = query_person_cost + "                                                                                                                                                                    "
query_person_cost = query_person_cost + " FROM (                                                                                                                                                             "
query_person_cost = query_person_cost + "                                                                                                                                                                    "
query_person_cost = query_person_cost + "     SELECT  A.EMP_NO          , GENERAL_CNT          , GENERAL_COST          , OVERTIME_CNT          , OVERTIME_COST                                               "
query_person_cost = query_person_cost + "           , GAS_KM            , GAS_UNIT             , GAS_COST              , GASOL_KM              , GASOL_UNIT                                                  "
query_person_cost = query_person_cost + "           , GASOL_COST        , DIESEL_KM            , DIESEL_UNIT           , DIESEL_COST           , SOMOPUM_COST                                                "
query_person_cost = query_person_cost + "           , FARE_CNT          , FARE_COST            , OIL_CASH_COST         , REPAIR_COST           , PARKING_COST                                                "
query_person_cost = query_person_cost + "           , TOLL_COST         , CARD_COST            , CARD_COST_VAT         , RETURN_CASH           , JUYOO_CARD_COST                                             "
query_person_cost = query_person_cost + "           , JUYOO_CARD_COST_VAT          , VARIATION_MEMO          , IF(J.CAR_OWNER='회사', B.GASOL_KM2 ,0) GASOL_KM2          , IF(J.CAR_OWNER='회사', B.DIESEL_KM2 ,0)   DIESEL_KM2          , IF(J.CAR_OWNER='회사', B.GAS_KM2 ,0)  GAS_KM2                                     "
query_person_cost = query_person_cost + "           , (CASE A.TEAM WHEN '본사팀'   THEN H.GAS_UNIT_1                                                                                                         "
query_person_cost = query_person_cost + "                                          WHEN 'SM1팀'    THEN H.GAS_UNIT_1                                                                                         "
query_person_cost = query_person_cost + "                                          WHEN 'Repair팀' THEN H.GAS_UNIT_1                                                                                         "
query_person_cost = query_person_cost + "                                          WHEN 'SM2팀'    THEN H.GAS_UNIT_1                                                                                         "
query_person_cost = query_person_cost + "                                          ELSE H.GAS_UNIT_2        END      ) AS GAS_UNIT2                                                                          "
query_person_cost = query_person_cost + "           , (CASE A.TEAM WHEN '본사팀'   THEN H.GASOL_UNIT_1                                                                                                       "
query_person_cost = query_person_cost + "                                          WHEN 'SM1팀'    THEN H.GASOL_UNIT_1                                                                                       "
query_person_cost = query_person_cost + "                                          WHEN 'Repair팀' THEN H.GASOL_UNIT_1                                                                                       "
query_person_cost = query_person_cost + "                                          WHEN 'SM2팀'    THEN H.GASOL_UNIT_1                                                                                       "
query_person_cost = query_person_cost + "                                          ELSE H.GASOL_UNIT_2        END      ) AS GASOL_UNIT2                                                                      "
query_person_cost = query_person_cost + "           , (CASE A.TEAM WHEN '본사팀'   THEN H.DIESEL_UNIT_1                                                                                                      "
query_person_cost = query_person_cost + "                                          WHEN 'SM1팀'    THEN H.DIESEL_UNIT_1                                                                                      "
query_person_cost = query_person_cost + "                                          WHEN 'Repair팀' THEN H.DIESEL_UNIT_1                                                                                      "
query_person_cost = query_person_cost + "                                          WHEN 'SM2팀'    THEN H.DIESEL_UNIT_1                                                                                      "
query_person_cost = query_person_cost + "                                          ELSE H.DIESEL_UNIT_2        END      ) AS DIESEL_UNIT2                                                                    "
query_person_cost = query_person_cost + "           , (CASE A.COMPANY WHEN '한화화약' THEN 8 ELSE 10 END) AS  LITER                                                                                          "
query_person_cost = query_person_cost + "           , IF(J.CAR_OWNER='회사', B.COMPANY_YN ,0)  COMPANY_YN                                                                                                                                        "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_07,0)    AS  GENERAL_COST_01                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_10,0)    AS  GENERAL_COST_02                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_02,0)    AS  GENERAL_COST_03                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_03,0)    AS  GENERAL_COST_04                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_04,0)    AS  GENERAL_COST_05                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_08,0)    AS  GENERAL_COST_06                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_05,0)    AS  GENERAL_COST_07                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_06,0)    AS  GENERAL_COST_08                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_01,0)    AS  GENERAL_COST_09                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_13,0)    AS  GENERAL_COST_10                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_20,0)    AS  GENERAL_COST_11                                                                                                     "
query_person_cost = query_person_cost + "           , IFNULL(I.GENERAL_COST_17,0)    AS  GENERAL_COST_12                                                                                                     "
query_person_cost = query_person_cost + "     FROM PERSON_COST A                                                                                                                                             "
query_person_cost = query_person_cost + "          LEFT JOIN (                                                                                                                                               "
query_person_cost = query_person_cost + "             SELECT MG_CE_ID                                                                                                                                        "
query_person_cost = query_person_cost + "                  , IFNULL(SUM(IF(G.CAR_OWNER='회사'  ,                                                                                                             "
query_person_cost = query_person_cost + "                         (CASE G.OIL_KIND WHEN '휘발유' THEN G.far ELSE 0 END),0)),0)         AS GASOL_KM2                                                          "
query_person_cost = query_person_cost + "                  , IFNULL(SUM(IF(G.CAR_OWNER='회사'  ,                                                                                                             "
query_person_cost = query_person_cost + "                         (CASE G.OIL_KIND WHEN '디젤' THEN G.far ELSE 0 END),0)) ,0)          AS DIESEL_KM2                                                         "
query_person_cost = query_person_cost + "                  , IFNULL(SUM(IF(G.CAR_OWNER='회사'  ,                                                                                                             "
query_person_cost = query_person_cost + "                         (CASE G.OIL_KIND WHEN '가스' THEN G.far ELSE 0 END),0)),0)           AS GAS_KM2                                                            "
query_person_cost = query_person_cost + "                  , IFNULL(SUM(CASE G.CAR_OWNER WHEN '회사' THEN 1 ELSE 0 END),0)             AS COMPANY_YN                                                         "
query_person_cost = query_person_cost + "                 FROM TRANSIT_COST G                                                                                                                                "
query_person_cost = query_person_cost + "                                                                                                                                                                    "
query_person_cost = query_person_cost + "              WHERE  1=1                                                                                                                                            "
query_person_cost = query_person_cost + "                AND G.RUN_DATE  >= ?                                                                                                                         "
query_person_cost = query_person_cost + "                AND G.RUN_DATE  <= ADDDATE(ADDDATE(?,INTERVAL 1 MONTH),-1)                                                                                   "
query_person_cost = query_person_cost + "                AND G.CANCEL_YN  = 'N'                                                                                                                              "
query_person_cost = query_person_cost + "                GROUP BY  MG_CE_ID                                                                                                                                  "
query_person_cost = query_person_cost + "           )B ON A.emp_no =B.MG_CE_ID                                                                                                                               "
query_person_cost = query_person_cost + "           LEFT JOIN (                                                                                                                                              "
query_person_cost = query_person_cost + "                 SELECT  EMP_NO                                                                                                                                     "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_01)  AS GENERAL_COST_01                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_02)  AS GENERAL_COST_02                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_03)  AS GENERAL_COST_03                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_04)  AS GENERAL_COST_04                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_05)  AS GENERAL_COST_05                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_06)  AS GENERAL_COST_06                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_07)  AS GENERAL_COST_07                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_08)  AS GENERAL_COST_08                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_09)  AS GENERAL_COST_09                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_10)  AS GENERAL_COST_10                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_11)  AS GENERAL_COST_11                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_12)  AS GENERAL_COST_12                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_13)  AS GENERAL_COST_13                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_14)  AS GENERAL_COST_14                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_15)  AS GENERAL_COST_15                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_16)  AS GENERAL_COST_16                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_17)  AS GENERAL_COST_17                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_18)  AS GENERAL_COST_18                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_19)  AS GENERAL_COST_19                                                                                                   "
query_person_cost = query_person_cost + "                        ,SUM(GENERAL_COST_20)  AS GENERAL_COST_20                                                                                                   "
query_person_cost = query_person_cost + "                 FROM (                                                                                                                                             "
query_person_cost = query_person_cost + "                                                                                                                                                                    "
query_person_cost = query_person_cost + "                 SELECT   EMP_NO                                                                                                                                    "
query_person_cost = query_person_cost + "                        , CASE account WHEN '통신비'      THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_01                                      "
query_person_cost = query_person_cost + "                        , CASE account WHEN '복리후생비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_02                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '접대비'      THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_03                                      "
query_person_cost = query_person_cost + "                        , CASE account WHEN '회의비'      THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_04                                      "
query_person_cost = query_person_cost + "                        , CASE account WHEN '소모품비'     THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_05                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '운반비'      THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_06                                      "
query_person_cost = query_person_cost + "                        , CASE account WHEN '차량유지비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_07                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '사무용품비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_08                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '잡금'       THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_09                                       "
query_person_cost = query_person_cost + "                        , CASE account WHEN '여비교통비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_10                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '광고선전비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_11                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '교육훈련비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_12                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '국내출장비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_13                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '도서인쇄비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_14                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '보험료'      THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_15                                      "
query_person_cost = query_person_cost + "                        , CASE account WHEN '잡비'       THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_16                                       "
query_person_cost = query_person_cost + "                        , CASE account WHEN '지급수수료'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_17                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '지급임차료'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_18                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '해외출장비'   THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_19                                     "
query_person_cost = query_person_cost + "                        , CASE account WHEN '수선비'      THEN  IF(F.PAY_YN='N',SUM(F.COST),0)  ELSE 0 END  AS GENERAL_COST_20                                      "
query_person_cost = query_person_cost + "                                                                                                                                                                    "
query_person_cost = query_person_cost + "                   FROM GENERAL_COST F                                                                                                                              "
query_person_cost = query_person_cost + "                  WHERE 1=1                                                                                                                                         "
query_person_cost = query_person_cost + "                    AND F.SLIP_GUBUN  = '비용'                                                                                                                      "
query_person_cost = query_person_cost + "                    AND F.TAX_BILL_YN NOT IN ('Y')                                                                                                                  "
query_person_cost = query_person_cost + "                    AND F.CANCEL_YN   = 'N'                                                                                                                         "
query_person_cost = query_person_cost + "                    AND F.SLIP_DATE  >= ?                                                                                                                    "
query_person_cost = query_person_cost + "                    AND F.SLIP_DATE  <= ADDDATE(ADDDATE(?,INTERVAL 1 MONTH),-1)                                                                              "
query_person_cost = query_person_cost + "                    GROUP BY EMP_NO,ACCOUNT,PAY_YN                                                                                                                  "
query_person_cost = query_person_cost + "                                 ) A                                                                                                                                "
query_person_cost = query_person_cost + "                 GROUP BY EMP_NO                                                                                                                                    "
query_person_cost = query_person_cost + "               ) I ON A.EMP_NO = I.EMP_NO                                                                                                                           "
query_person_cost = query_person_cost + "          LEFT JOIN(  "
query_person_cost = query_person_cost + "              select car_owner ,owner_emp_no"
query_person_cost = query_person_cost + "              from car_info "
query_person_cost = query_person_cost + "              group by   owner_emp_no"
query_person_cost = query_person_cost + "          ) J ON A.EMP_NO = J.owner_emp_no"
query_person_cost = query_person_cost + "           CROSS JOIN(                                                                                                                                              "
query_person_cost = query_person_cost + "                 SELECT  SUM(IF(OIL_UNIT_ID ='1' ,(CASE OIL_KIND WHEN '가스'   THEN OIL_UNIT_AVERAGE ELSE 0 END),0)) AS GAS_UNIT_1                                  "
query_person_cost = query_person_cost + "                        ,SUM(IF(OIL_UNIT_ID ='1' ,(CASE OIL_KIND WHEN '휘발유' THEN OIL_UNIT_AVERAGE ELSE 0 END),0)) AS GASOL_UNIT_1                                "
query_person_cost = query_person_cost + "                        ,SUM(IF(OIL_UNIT_ID ='1' ,(CASE OIL_KIND WHEN '디젤'   THEN OIL_UNIT_AVERAGE ELSE 0 END),0)) AS DIESEL_UNIT_1                               "
query_person_cost = query_person_cost + "                        ,SUM(IF(OIL_UNIT_ID ='2' ,(CASE OIL_KIND WHEN '가스'   THEN OIL_UNIT_AVERAGE ELSE 0 END),0)) AS GAS_UNIT_2                                  "
query_person_cost = query_person_cost + "                        ,SUM(IF(OIL_UNIT_ID ='2' ,(CASE OIL_KIND WHEN '휘발유' THEN OIL_UNIT_AVERAGE ELSE 0 END),0)) AS GASOL_UNIT_2                                "
query_person_cost = query_person_cost + "                        ,SUM(IF(OIL_UNIT_ID ='2' ,(CASE OIL_KIND WHEN '디젤'   THEN OIL_UNIT_AVERAGE ELSE 0 END),0)) AS DIESEL_UNIT_2                               "
query_person_cost = query_person_cost + "                  FROM OIL_UNIT                                                                                                                                     "
query_person_cost = query_person_cost + "                 WHERE OIL_UNIT_MONTH = CONCAT(SUBSTRING(?,1,4),SUBSTRING(?,6,2))                                                                     "
query_person_cost = query_person_cost + "           )H                                                                                                                                                       "
query_person_cost = query_person_cost + "     WHERE  A.cost_month =  CONCAT(SUBSTRING(?,1,4),SUBSTRING(?,6,2))                                                                                 "
query_person_cost = query_person_cost + "     AND A.emp_no =?                                                                                                                                         "
query_person_cost = query_person_cost + "  ) A"



%>
