spring:
  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true
      path: /h2-console

  # 실제 데이터베이스 접속 정보
  datasource:
    url: jdbc:h2:~/erpdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # ORM 데이터베이스, 테이블 변경사항 옵션
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # format_sql: true
        # show_sql: true
    hibernate:
      ddl-auto: update

  # Thymeleaf 캐시 사용하지 않음
  thymeleaf:
    cache: false
  # devtools:
  #   livereload:
  #     enabled: true
  #   restart:
  #     enabled: true

logging:
  level:
    "[com.mysite.spring-erp]": DEBUG

server:
  port: 8091
